### ISSUE TITLE
Initial load of tab screens rendered twice

### ISSUE THREAD

**Issue by goufang** [web-ridge/react-native-paper-tabs#15]
Is there a way to prevent all screens from re-rendering on initial load?

Thanks

**Comment by RichardLindhout** [comment]
Wrap the subscreen in a React.memo should fix it there. Does this happen on the web version or ios/android?

**Comment by goufang** [comment]
they are already wrapper with React.memo however still no luck. Also, each swipe action all of the TabScreens are loaded as well.

**Comment by RichardLindhout** [comment]
Where do you put the React.memo? do you use the use the `useTabIndex()`?

**Comment by RichardLindhout** [comment]
You need to
```tsx
  <TabScreen label="Flights" icon="airplane">
          <Flights />
        </TabScreen>
```

Flights.tsx/js
```tsx
function Flights(){
console.log('re render flights')
     return View style={{ backgroundColor: 'black', flex:1 }} />
}
export default React.memo(Flights)
```

**Comment by CristianFigueredo** [comment]
Hi @RichardLindhout, thanks for this library, I have the same problem, I already apply React.Memo, also all the TabScreens are rendered at the beginning

(I'm using Expo, the project is in production, iOS and Android)

**Comment by CristianFigueredo** [comment]
Hi, thanks for this library, I have the same problem, I already apply React.Memo, also all the TabScreens are rendered at the beginning

(I'm using Expo, the project is in production, iOS and Android)

**Comment by RichardLindhout** [comment]
Please provide a simple snack
