### ISSUE TITLE
setNativeProps is not a function (@expo/vector-icons 14+)

### ISSUE THREAD

**Issue by sawankumar1012** [web-ridge/react-native-paper-tabs#74]
### Current behaviour
it shows error  ERROR  TypeError: this._icon.setNativeProps is not a function (it is undefined), js engine: hermes

### How to reproduce?
installing and adding the component will reproduce the error 

### Preview

<img width="1424" alt="Screenshot 2024-07-24 at 12 34 51 PM" src="https://github.com/user-attachments/assets/8d7074a1-c294-418f-b01b-eb55042ad40f">

<img width="310" alt="Screenshot 2024-07-24 at 12 38 44 PM" src="https://github.com/user-attachments/assets/1d9b598d-e4e0-49aa-975b-ba28f638aba7">

**Comment by amelongo** [comment]
@sawankumar1012 @RichardLindhout 

I have this exact issue and I really don't know how to resolve it. It seems the component is out of sync with the "react-native-vector-icons" library. When I remove the 'icon' prop from the TabScreen component, this error goes away; however, I would really much want to have the icons.
Any update on this?

**Comment by stefano-vergani** [comment]
Same problem here ... any up?

**Comment by RichardLindhout** [comment]
We don't use setNativeProps? Maybe somewhere in a dependency e.g. react native paper?

**Comment by RichardLindhout** [comment]
https://github.com/web-ridge/react-native-paper-tabs/issues/65

**Comment by RichardLindhout** [comment]
Somebody got time for a PR. I'm really busy right now unfortunately to get to the bottom of this.

**Comment by RichardLindhout** [comment]
For now @expo/vector-icons": "^13.0.0 seems to work according to comments on another issue

**Comment by RichardLindhout** [comment]
https://github.com/expo/vector-icons/issues/308

**Comment by RichardLindhout** [comment]
Still not working because expo vector icons don't support animatable somehow

**Comment by RichardLindhout** [comment]
I created snack for expo-team so hopefully they will fix this :)
https://snack.expo.dev/@richardlindhout/expo-animated-icon-error

**Comment by RichardLindhout** [comment]
This is fixed now by us using useNativeDriver: true + not animated color of icon on android (since that gives another strange error) and material you does not animate color of icon anyways anymore

**Comment by amelongo** [comment]
Richard,
I did the test on Snack and it's still not working.
See attached.
Thanks
    On Tuesday, January 7, 2025 at 12:10:23 PM PST, Richard Lindhout ***@***.***> wrote:  
 
 


I created snack for expo-team so hopefully they will fix this :)
***@***.***/expo-animated-icon-error

**Comment by ajay-at-memorang** [comment]
Still reproducible in version `0.11.3`
